language: node_js

cache:
  directories:
    - node_modules

node_js:
  - '10'
  - '11'
  - '8'

stages:
  - name: test
  - name: build
  - name: release
    if: branch = master

jobs:
  include:
    - stage: build
      install:
        - npm install
      script:
        - npm run build

    - stage: test
      install:
        - npm install
      script:
        - npm run test:prod

    - stage: release
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
