language: node_js

install:
  - yarn

cache:
  yarn: true
  directories:
    - node_modules

node_js:
  - '10'
  - '11'
  - '8'

stages:
  - name: test
  - name: build
  - name: release
    if: branch = master

jobs:
  include:
    - stage: test
      install:
        - yarn install
      script:
        - yarn test:prod

    - stage: build
      install:
        - yarn install
      script:
        - yarn build

    - stage: release
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn semantic-release
